export const playerDatabase = [
  // --- MENS SUPERSTARS ---
  { id: 1, name: "Rohit Sharma", role: "Batter", team: "IND", batRating: 92, bowlRating: 15, style: "Aggressive" },
  { id: 2, name: "Virat Kohli", role: "Batter", team: "IND", batRating: 95, bowlRating: 10, style: "Anchor" },
  { id: 3, name: "Suryakumar Yadav", role: "Batter", team: "IND", batRating: 94, bowlRating: 5, style: "Aggressive" },
  { id: 4, name: "Jasprit Bumrah", role: "Bowler", team: "IND", batRating: 15, bowlRating: 98, style: "Pace" },
  { id: 5, name: "Travis Head", role: "Batter", team: "AUS", batRating: 91, bowlRating: 20, style: "Aggressive" },
  { id: 6, name: "Pat Cummins", role: "Bowler", team: "AUS", batRating: 45, bowlRating: 94, style: "Pace" },
  { id: 7, name: "Mitchell Starc", role: "Bowler", team: "AUS", batRating: 30, bowlRating: 92, style: "Pace" },
  { id: 8, name: "Jos Buttler", role: "Batter", team: "ENG", batRating: 92, bowlRating: 0, style: "Aggressive" },
  { id: 9, name: "Jofra Archer", role: "Bowler", team: "ENG", batRating: 25, bowlRating: 89, style: "Pace" },
  { id: 10, name: "Kagiso Rabada", role: "Bowler", team: "RSA", batRating: 20, bowlRating: 93, style: "Pace" },
  { id: 11, name: "Babar Azam", role: "Batter", team: "PAK", batRating: 92, bowlRating: 0, style: "Anchor" },
  { id: 12, name: "Shaheen Afridi", role: "Bowler", team: "PAK", batRating: 35, bowlRating: 91, style: "Pace" },
  { id: 13, name: "Kane Williamson", role: "Batter", team: "NZ", batRating: 93, bowlRating: 15, style: "Anchor" },
  { id: 14, name: "Rashid Khan", role: "All-Rounder", team: "AFG", batRating: 75, bowlRating: 96, style: "Spin" },
  { id: 15, name: "Hardik Pandya", role: "All-Rounder", team: "IND", batRating: 85, bowlRating: 82, style: "Finisher" },
  { id: 16, name: "Ravindra Jadeja", role: "All-Rounder", team: "IND", batRating: 80, bowlRating: 88, style: "Anchor" },
  { id: 17, name: "Glenn Maxwell", role: "All-Rounder", team: "AUS", batRating: 88, bowlRating: 75, style: "Finisher" },
  { id: 18, name: "Heinrich Klaasen", role: "Batter", team: "RSA", batRating: 94, bowlRating: 0, style: "Finisher" },
  { id: 19, name: "Ben Stokes", role: "All-Rounder", team: "ENG", batRating: 88, bowlRating: 80, style: "Finisher" },
  { id: 20, name: "Kuldeep Yadav", role: "Bowler", team: "IND", batRating: 10, bowlRating: 86, style: "Spin" },

  // --- WPL WOMENS SUPERSTARS ---
  { id: 101, name: "Smriti Mandhana", role: "Batter", team: "RCB-W", batRating: 95, bowlRating: 10, style: "Aggressive" },
  { id: 102, name: "Harmanpreet Kaur", role: "Batter", team: "MI-W", batRating: 94, bowlRating: 20, style: "Aggressive" },
  { id: 103, name: "Nat Sciver-Brunt", role: "All-Rounder", team: "MI-W", batRating: 94, bowlRating: 85, style: "Aggressive" },
  { id: 104, name: "Lizelle Lee", role: "Batter", team: "DC-W", batRating: 90, bowlRating: 0, style: "Aggressive" },
  { id: 105, name: "Laura Wolvaardt", role: "Batter", team: "DC-W", batRating: 91, bowlRating: 0, style: "Anchor" },
  { id: 106, name: "Sophie Devine", role: "All-Rounder", team: "GG-W", batRating: 88, bowlRating: 92, style: "Finisher" },
  { id: 107, name: "Meg Lanning", role: "Batter", team: "UPW", batRating: 92, bowlRating: 0, style: "Anchor" },
  { id: 108, name: "Ashleigh Gardner", role: "All-Rounder", team: "GG-W", batRating: 88, bowlRating: 85, style: "Aggressive" },
  { id: 109, name: "Amelia Kerr", role: "All-Rounder", team: "MI-W", batRating: 85, bowlRating: 90, style: "Spin" },
  { id: 110, name: "Marizanne Kapp", role: "All-Rounder", team: "DC-W", batRating: 80, bowlRating: 88, style: "Pace" },
  { id: 111, name: "Ellyse Perry", role: "All-Rounder", team: "RCB-W", batRating: 89, bowlRating: 84, style: "Anchor" },
  { id: 112, name: "Deepti Sharma", role: "All-Rounder", team: "UPW", batRating: 84, bowlRating: 87, style: "Spin" },
  { id: 113, name: "Shafali Verma", role: "Batter", team: "DC-W", batRating: 88, bowlRating: 15, style: "Aggressive" },
  { id: 114, name: "Sophie Ecclestone", role: "Bowler", team: "UPW", batRating: 20, bowlRating: 95, style: "Spin" },
  { id: 115, name: "Shabnim Ismail", role: "Bowler", team: "MI-W", batRating: 15, bowlRating: 93, style: "Pace" },
  { id: 116, name: "Renuka Singh", role: "Bowler", team: "RCB-W", batRating: 10, bowlRating: 89, style: "Pace" },
  { id: 117, name: "Richa Ghosh", role: "Batter", team: "RCB-W", batRating: 87, bowlRating: 0, style: "Finisher" },
  { id: 118, name: "Jemimah Rodrigues", role: "Batter", team: "DC-W", batRating: 86, bowlRating: 0, style: "Anchor" },
  { id: 119, name: "Beth Mooney", role: "Batter", team: "GG-W", batRating: 90, bowlRating: 0, style: "Anchor" },
  { id: 120, name: "Radha Yadav", role: "Bowler", team: "RCB-W", batRating: 15, bowlRating: 87, style: "Spin" },
  { id: 121, name: "Shikha Pandey", role: "Bowler", team: "UPW", batRating: 30, bowlRating: 86, style: "Pace" },
  { id: 122, name: "Phoebe Litchfield", role: "Batter", team: "UPW", batRating: 85, bowlRating: 0, style: "Aggressive" }
];