export const playerDatabase = [
  // --- FULL SQUAD: MUMBAI INDIANS (MI) ---
  { id: 1, name: "Rohit Sharma", role: "Batter", team: "MI", batRating: 92, bowlRating: 15, style: "Aggressive" },
  { id: 2, name: "Ishan Kishan", role: "Batter", team: "MI", batRating: 88, bowlRating: 0, style: "Aggressive" },
  { id: 3, name: "Suryakumar Yadav", role: "Batter", team: "MI", batRating: 95, bowlRating: 5, style: "Aggressive" },
  { id: 4, name: "Tilak Varma", role: "Batter", team: "MI", batRating: 86, bowlRating: 20, style: "Anchor" },
  { id: 5, name: "Hardik Pandya", role: "All-Rounder", team: "MI", batRating: 89, bowlRating: 85, style: "Finisher" },
  { id: 6, name: "Tim David", role: "Batter", team: "MI", batRating: 85, bowlRating: 10, style: "Finisher" },
  { id: 7, name: "Mohammad Nabi", role: "All-Rounder", team: "MI", batRating: 75, bowlRating: 84, style: "Spin" },
  { id: 8, name: "Piyush Chawla", role: "Bowler", team: "MI", batRating: 30, bowlRating: 82, style: "Spin" },
  { id: 9, name: "Gerald Coetzee", role: "Bowler", team: "MI", batRating: 25, bowlRating: 87, style: "Pace" },
  { id: 10, name: "Jasprit Bumrah", role: "Bowler", team: "MI", batRating: 15, bowlRating: 98, style: "Pace" },
  { id: 11, name: "Nuwan Thushara", role: "Bowler", team: "MI", batRating: 10, bowlRating: 86, style: "Pace" },

  // --- FULL SQUAD: CHENNAI SUPER KINGS (CSK) ---
  { id: 12, name: "Ruturaj Gaikwad", role: "Batter", team: "CSK", batRating: 90, bowlRating: 0, style: "Anchor" },
  { id: 13, name: "Rachin Ravindra", role: "All-Rounder", team: "CSK", batRating: 86, bowlRating: 75, style: "Aggressive" },
  { id: 14, name: "Ajinkya Rahane", role: "Batter", team: "CSK", batRating: 84, bowlRating: 0, style: "Anchor" },
  { id: 15, name: "Shivam Dube", role: "All-Rounder", team: "CSK", batRating: 88, bowlRating: 40, style: "Aggressive" },
  { id: 16, name: "Daryl Mitchell", role: "All-Rounder", team: "CSK", batRating: 87, bowlRating: 60, style: "Aggressive" },
  { id: 17, name: "Ravindra Jadeja", role: "All-Rounder", team: "CSK", batRating: 82, bowlRating: 88, style: "Finisher" },
  { id: 18, name: "MS Dhoni", role: "Batter", team: "CSK", batRating: 85, bowlRating: 0, style: "Finisher" },
  { id: 19, name: "Deepak Chahar", role: "Bowler", team: "CSK", batRating: 35, bowlRating: 86, style: "Pace" },
  { id: 20, name: "Maheesh Theekshana", role: "Bowler", team: "CSK", batRating: 20, bowlRating: 85, style: "Spin" },
  { id: 21, name: "Mustafizur Rahman", role: "Bowler", team: "CSK", batRating: 10, bowlRating: 88, style: "Pace" },
  { id: 22, name: "Matheesha Pathirana", role: "Bowler", team: "CSK", batRating: 5, bowlRating: 92, style: "Pace" },

  // --- FULL SQUAD: ROYAL CHALLENGERS BENGALURU (RCB) ---
  { id: 23, name: "Faf du Plessis", role: "Batter", team: "RCB", batRating: 89, bowlRating: 0, style: "Anchor" },
  { id: 24, name: "Virat Kohli", role: "Batter", team: "RCB", batRating: 95, bowlRating: 10, style: "Anchor" },
  { id: 25, name: "Rajat Patidar", role: "Batter", team: "RCB", batRating: 85, bowlRating: 0, style: "Aggressive" },
  { id: 26, name: "Glenn Maxwell", role: "All-Rounder", team: "RCB", batRating: 88, bowlRating: 75, style: "Finisher" },
  { id: 27, name: "Cameron Green", role: "All-Rounder", team: "RCB", batRating: 86, bowlRating: 80, style: "Aggressive" },
  { id: 28, name: "Dinesh Karthik", role: "Batter", team: "RCB", batRating: 84, bowlRating: 0, style: "Finisher" },
  { id: 29, name: "Mahipal Lomror", role: "All-Rounder", team: "RCB", batRating: 78, bowlRating: 60, style: "Aggressive" },
  { id: 30, name: "Karn Sharma", role: "Bowler", team: "RCB", batRating: 25, bowlRating: 82, style: "Spin" },
  { id: 31, name: "Lockie Ferguson", role: "Bowler", team: "RCB", batRating: 15, bowlRating: 88, style: "Pace" },
  { id: 32, name: "Mohammed Siraj", role: "Bowler", team: "RCB", batRating: 15, bowlRating: 89, style: "Pace" },
  { id: 33, name: "Yash Dayal", role: "Bowler", team: "RCB", batRating: 10, bowlRating: 84, style: "Pace" },

  // --- FULL SQUAD: RCB WOMEN (RCB-W) ---
  { id: 101, name: "Smriti Mandhana", role: "Batter", team: "RCB-W", batRating: 95, bowlRating: 10, style: "Aggressive" },
  { id: 102, name: "Sophie Devine", role: "All-Rounder", team: "RCB-W", batRating: 90, bowlRating: 85, style: "Aggressive" },
  { id: 103, name: "Ellyse Perry", role: "All-Rounder", team: "RCB-W", batRating: 94, bowlRating: 86, style: "Anchor" },
  { id: 104, name: "Richa Ghosh", role: "Batter", team: "RCB-W", batRating: 88, bowlRating: 0, style: "Finisher" },
  { id: 105, name: "S. Meghana", role: "Batter", team: "RCB-W", batRating: 78, bowlRating: 0, style: "Aggressive" },
  { id: 106, name: "Georgia Wareham", role: "All-Rounder", team: "RCB-W", batRating: 75, bowlRating: 88, style: "Spin" },
  { id: 107, name: "Sophie Molineux", role: "All-Rounder", team: "RCB-W", batRating: 70, bowlRating: 89, style: "Spin" },
  { id: 108, name: "Shreyanka Patil", role: "Bowler", team: "RCB-W", batRating: 40, bowlRating: 87, style: "Spin" },
  { id: 109, name: "Asha Shobana", role: "Bowler", team: "RCB-W", batRating: 20, bowlRating: 85, style: "Spin" },
  { id: 110, name: "Renuka Singh", role: "Bowler", team: "RCB-W", batRating: 15, bowlRating: 89, style: "Pace" },
  { id: 111, name: "Ekta Bisht", role: "Bowler", team: "RCB-W", batRating: 10, bowlRating: 82, style: "Spin" },

  // --- FULL SQUAD: MI WOMEN (MI-W) ---
  { id: 112, name: "Hayley Matthews", role: "All-Rounder", team: "MI-W", batRating: 92, bowlRating: 88, style: "Aggressive" },
  { id: 113, name: "Yastika Bhatia", role: "Batter", team: "MI-W", batRating: 84, bowlRating: 0, style: "Aggressive" },
  { id: 114, name: "Nat Sciver-Brunt", role: "All-Rounder", team: "MI-W", batRating: 95, bowlRating: 89, style: "Anchor" },
  { id: 115, name: "Harmanpreet Kaur", role: "Batter", team: "MI-W", batRating: 93, bowlRating: 40, style: "Aggressive" },
  { id: 116, name: "Amelia Kerr", role: "All-Rounder", team: "MI-W", batRating: 86, bowlRating: 93, style: "Spin" },
  { id: 117, name: "Pooja Vastrakar", role: "All-Rounder", team: "MI-W", batRating: 78, bowlRating: 82, style: "Pace" },
  { id: 118, name: "Amanjot Kaur", role: "All-Rounder", team: "MI-W", batRating: 75, bowlRating: 70, style: "Finisher" },
  { id: 119, name: "Sajeevan Sajana", role: "Batter", team: "MI-W", batRating: 76, bowlRating: 0, style: "Finisher" },
  { id: 120, name: "Shabnim Ismail", role: "Bowler", team: "MI-W", batRating: 20, bowlRating: 94, style: "Pace" },
  { id: 121, name: "Saika Ishaque", role: "Bowler", team: "MI-W", batRating: 15, bowlRating: 86, style: "Spin" },
  { id: 122, name: "Issy Wong", role: "Bowler", team: "MI-W", batRating: 10, bowlRating: 83, style: "Pace" },

  // --- INTERNATIONAL SUPERSTARS (For Custom Drafts) ---
  { id: 201, name: "Travis Head", role: "Batter", team: "AUS", batRating: 91, bowlRating: 20, style: "Aggressive" },
  { id: 202, name: "Pat Cummins", role: "Bowler", team: "AUS", batRating: 45, bowlRating: 94, style: "Pace" },
  { id: 203, name: "Mitchell Starc", role: "Bowler", team: "AUS", batRating: 30, bowlRating: 92, style: "Pace" },
  { id: 204, name: "Jos Buttler", role: "Batter", team: "ENG", batRating: 92, bowlRating: 0, style: "Aggressive" },
  { id: 205, name: "Jofra Archer", role: "Bowler", team: "ENG", batRating: 25, bowlRating: 89, style: "Pace" },
  { id: 206, name: "Kagiso Rabada", role: "Bowler", team: "RSA", batRating: 20, bowlRating: 93, style: "Pace" },
  { id: 207, name: "Babar Azam", role: "Batter", team: "PAK", batRating: 92, bowlRating: 0, style: "Anchor" },
  { id: 208, name: "Shaheen Afridi", role: "Bowler", team: "PAK", batRating: 35, bowlRating: 91, style: "Pace" },
  { id: 209, name: "Kane Williamson", role: "Batter", team: "NZ", batRating: 93, bowlRating: 15, style: "Anchor" },
  { id: 210, name: "Rashid Khan", role: "All-Rounder", team: "AFG", batRating: 75, bowlRating: 96, style: "Spin" },
];